var t1 = [
    "HTTP Request + Headers",
    "HTTP Status Codes",
    "Editor, IDE",
    "Zusammenspiel HTML, CSS, JS",
    "HTML Grundgerüst",
    "Block, Inline, andere Displayarten",
    "Semantik",
    "Hyperlinks",
    "Formulare",
    "CSS Regel",
    "CSS Selektoren, Kaskadierung",
    "Box Modell","Flexbox",
    "Pseudoklassen, Pseudoelemente","Mediaqueries","Bootstrap","JS Code einbetten","Datentypen, Variablen","Conditions","Operatoren, Logikoperatoren","mathematische Funktionen","Funktionen (allgemeine Verwendung)","Schleifen","Arrays","Objekte","DOM (Manipulation, Traversing)","DOM Elemente erzeugen","Navigator und Location‐Objekt","Querystring","Errorhandling, Debuggen","Stringmethoden","Date‐Objekt","reguläre Ausdrücke","Callbacks, Closure‐Funktionen","this","Arrowfunktionen, Templatestrings","Eventhandler, Eventbubbling","Formularfelder (input, select, Radiobuttons, etc.)","Single Page Applikation","AJAX, XHR, CORS","JSON, XML, CSV","Synchrone, Asynchrone Programmabläufe","Zeitfunktionen (Timeout, Interval, requestAnimationFrame)","jQuery","Method‐Chaining","Tastatur‐Ereignisse","Storage im Browser (inkl. Cookies)","SVG","Canvas","Promise (await, async)","Konstruktorfunktion","OOP","Klassen, Subklassen","Setter, Getter","Objekt‐Properties","Arraymethoden (sort, map, filter)","Maps, Sets, Symbole","Prototype‐Objekt","import/export","ECMAScript6  ","Geolocation","Filereader","Mediastream","Webworker","iFrames"
]

var t2 = [
    "SCM, GIT",
    "Agiles Projektmanagament",
    "Wireframes, Mockups, Flowcharts",
    "Lasten‐ und Pflichtenheft",
    "Requirements Engineering",
    "UI/UX",
    "NPM",
    "CI/CD (continues integration/development)",
    "Laufzeitumgebungen JS",
    "NodeJS ",
    "Zugriff Dateisystem (fs)",
    "http‐Modul",
    "Websockets (vs. XHR)",
    "Eventdriven, IPC",
    "Module",
    "HTTPS",
    "Routing",
    "MVC",
    "express",
    "Template Engines",
    "SQL Datenbank",
    "NoSQL Datenbank",
    "REST/CRUD",
    "Authentification (JWT od. passport)",
    "Postman, cURL",
    "Prozesse, Subprozesse",
    "Streams",
    "Testdriven (TDD)",
    "Electron (Fenster, Menü)",
    "Desktopapplikation Besonderheiten",
    "Touchevents, weitere Device‐Events",
    "PWA",
    "Cordova",
    "Angular, React und Vue",
    "Publishing Mobile App"
]
var table1 = function () { return t1};
var table2 = function () { return t2};
